In [84]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier

# Data exploration

In [64]:
df = pd.read_csv("../data/dataset.csv", sep=";")

In [65]:
df.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [66]:
df.shape

(45211, 17)

In [67]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [68]:
df

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

# Data preparation

In [69]:
numerical_features = [
    "age",
    "balance",
    "day",
    "duration",
    "campaign",
    "pdays",
    "previous",
]
categorical_features = ["job", "marital", "education", "contact", "month", "poutcome"]
binary_features = ["default", "housing", "loan"]

In [70]:
df["y"] = df["y"].map({"yes": 1, "no": 0})
df["default"] = df["default"].map({"yes": 1, "no": 0})
df["housing"] = df["housing"].map({"yes": 1, "no": 0})
df["loan"] = df["loan"].map({"yes": 1, "no": 0})

In [71]:
df["y"]

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: y, Length: 45211, dtype: int64

In [72]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_features,
        ),  # Z-score scaling for continuous features
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore", sparse_output=False),
            categorical_features,
        ),  # OHE for nominal features
    ],
    # Pass through the already encoded/binary features
    remainder="passthrough",
)

In [73]:
preprocessed_df = preprocessor.fit_transform(df)
preprocessor.get_feature_names_out()

array(['num__age', 'num__balance', 'num__day', 'num__duration',
       'num__campaign', 'num__pdays', 'num__previous', 'cat__job_admin.',
       'cat__job_blue-collar', 'cat__job_entrepreneur',
       'cat__job_housemaid', 'cat__job_management', 'cat__job_retired',
       'cat__job_self-employed', 'cat__job_services', 'cat__job_student',
       'cat__job_technician', 'cat__job_unemployed', 'cat__job_unknown',
       'cat__marital_divorced', 'cat__marital_married',
       'cat__marital_single', 'cat__education_primary',
       'cat__education_secondary', 'cat__education_tertiary',
       'cat__education_unknown', 'cat__contact_cellular',
       'cat__contact_telephone', 'cat__contact_unknown', 'cat__month_apr',
       'cat__month_aug', 'cat__month_dec', 'cat__month_feb',
       'cat__month_jan', 'cat__month_jul', 'cat__month_jun',
       'cat__month_mar', 'cat__month_may', 'cat__month_nov',
       'cat__month_oct', 'cat__month_sep', 'cat__poutcome_failure',
       'cat__poutcome_other',

In [74]:
preprocessed_df[:, -1]

array([0., 0., 0., ..., 1., 0., 0.], shape=(45211,))

In [75]:
preprocessed_df[:, 0]

array([ 1.60696496,  0.28852927, -0.74738448, ...,  2.92540065,
        1.51279098, -0.37068857], shape=(45211,))

In [76]:
preprocessed_df[:, 7:19]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], shape=(45211, 12))

# Model training

In [77]:
positive_count = df["y"].sum()
negative_count = len(df) - positive_count
scale_weight = negative_count / positive_count
print(positive_count, negative_count, scale_weight)

5289 39922 7.548118737001324


In [79]:
xgb_model = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_estimators=500,
    learning_rate=0.05,
    scale_pos_weight=scale_weight,
)

In [80]:
full_pipeline = Pipeline(
    steps=[("preprocessor", preprocessor), ("classifier", xgb_model)]
)

In [81]:
X = df.drop(columns=["y"])
y = df["y"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [83]:
full_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['age', 'balance', 'day',
                                                   'duration', 'campaign',
                                                   'pdays', 'previous']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['job', 'marital',
                                                   'education', 'contact',
                                                   'month', 'poutcome'])])),
                ('classifier',
                 XGBClassifier(base_score=None...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=500, n_jobs=None,
                               num_parallel_tree=None, ...))])

# Model evaluation

In [86]:
y_pred_proba = full_pipeline.predict_proba(X_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_pred_proba)
print(roc_auc)

0.9307509472510486


In [88]:
y_pred_proba

array([0.00242634, 0.0039907 , 0.01371909, ..., 0.28812438, 0.00509653,
       0.05887718], shape=(9043,), dtype=float32)

In [91]:
np.count_nonzero(y_pred_proba > 0.5) / len(y_pred_proba)

np.float64(0.2091120203472299)

# Model with split `pdays`

Motivation: -1 does not bear semantic value in the scope of `pdays`, e.g., with the same distance to 0, -1 bears a totally different meaning to 1. -1 is essentially a flag of previous contact.

Experiment: create a new feature based on the -1 value of `pdays` and impute the original -1 with the median of the non--1 values, train and evalute a new model.

Observation: the new model does not yield better result than the previous model, mainly because previous contact has been captured by other features, e.g., `previous` leading to redundancy.

In [95]:
df2 = pd.read_csv("../data/dataset.csv", sep=";")

df2["y"] = df2["y"].map({"yes": 1, "no": 0})
df2["default"] = df2["default"].map({"yes": 1, "no": 0})
df2["housing"] = df2["housing"].map({"yes": 1, "no": 0})
df2["loan"] = df2["loan"].map({"yes": 1, "no": 0})

df2["was_contacted_prev"] = (df2["pdays"] != -1).astype(int)
pdays_median = df2.loc[df2["pdays"] != -1, "pdays"].median()
df2["pdays_cleaned"] = df2["pdays"].replace(-1, pdays_median)

In [96]:
numerical_features2 = [
    "age",
    "balance",
    "day",
    "duration",
    "campaign",
    "previous",
    "pdays_cleaned",
]
categorical_features2 = ["job", "marital", "education", "contact", "month", "poutcome"]
binary_features2 = ["default", "housing", "loan", "was_contacted_prev"]

In [97]:
preprocessor2 = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features2),
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore", sparse_output=False),
            categorical_features2,
        ),
    ],
    remainder="passthrough",
)

In [99]:
positive_count2 = df2["y"].sum()
negative_count2 = len(df2) - positive_count2
scale_weight2 = negative_count2 / positive_count2
print(positive_count2, negative_count2, scale_weight2)

5289 39922 7.548118737001324


In [100]:
xgb_model2 = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_estimators=500,
    learning_rate=0.05,
    scale_pos_weight=scale_weight2,
)

In [101]:
full_pipeline2 = Pipeline(
    steps=[("preprocessor", preprocessor2), ("classifier", xgb_model2)]
)

In [102]:
X2 = df2.drop(columns=["y", "pdays"])
y2 = df2["y"]

X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X2, y2, test_size=0.2, stratify=y2, random_state=42
)

In [104]:
full_pipeline2.fit(X_train2, y_train2)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['age', 'balance', 'day',
                                                   'duration', 'campaign',
                                                   'previous',
                                                   'pdays_cleaned']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['job', 'marital',
                                                   'education', 'contact',
                                                   'month', 'poutcome'])])),
                ('classifier',
                 XGBClassifier(base_sc...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=500, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [105]:
y_pred_proba2 = full_pipeline2.predict_proba(X_test2)[:, 1]
roc_auc2 = roc_auc_score(y_test2, y_pred_proba2)
print(roc_auc2)

0.9297914449706622
